# Lab 2 exercise 5

In [70]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [71]:
t1 = pd.read_csv('data/13.1.csv', usecols=[0,1], encoding='latin-1')
t1.columns = ['label','body']
t1['label'] = t1['label'].replace(["no","yes"],[0,1])
# t1 = t1.values
t2 = pd.read_csv('data/13.10.csv', usecols=[0,1], encoding='latin-1')
t2.columns = ['label','body']
t2['label'] = t2['label'].replace(["no","yes"],[0,1])
# t2 = t2.values
t3 = pd.read_csv('data/IAML.csv', usecols=[0,1], encoding='latin-1')
t3.columns = ['label','body']
t3['label'] = t3['label'].replace(["ham","spam"],[0,1])
# t3 = t3.values

# Pre-Processing

In [72]:
t1['body'] = t1.body.map(lambda x: x.lower())
t1['body'] = t1.body.str.replace('[^\w\s]', '')
t1

label                                 body
0      1              chinese beijing chinese
1      1             chinese chinese shanghai
2      1                        chinese macao
3      0                  tokyo japan chinese
4      1  chinese chinese chinese tokyo japan

In [73]:
t2['body'] = t2.body.map(lambda x: x.lower())
t2['body'] = t2.body.str.replace('[^\w\s]', '')
t2

label                   body
0      1          taipei taiwan
1      1  macao taiwan shanghai
2      0          japan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo

In [74]:
t3['body'] = t3.body.map(lambda x: x.lower())
t3['body'] = t3.body.str.replace('[^\w\s]', '')
t3

label                   body
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password
5      1   send us your account
6      0          review us now

In [75]:
import nltk
nltk.download('punkt')

t1['body'] = t1['body'].apply(nltk.word_tokenize)
t1.head()

[nltk_data] Downloading package punkt to /home/mike/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


label                                       body
0      1                [chinese, beijing, chinese]
1      1               [chinese, chinese, shanghai]
2      1                           [chinese, macao]
3      0                    [tokyo, japan, chinese]
4      1  [chinese, chinese, chinese, tokyo, japan]

In [76]:
t2['body'] = t2['body'].apply(nltk.word_tokenize)
t2.head()

label                       body
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0           [japan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]

In [77]:
t3['body'] = t3['body'].apply(nltk.word_tokenize)
t3

label                        body
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]
5      1   [send, us, your, account]
6      0           [review, us, now]

In [78]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [79]:
t1['body'] = t1['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t1.head()

label                                    body
0      1                  [chines, beij, chines]
1      1              [chines, chines, shanghai]
2      1                         [chines, macao]
3      0                  [tokyo, japan, chines]
4      1  [chines, chines, chines, tokyo, japan]

In [80]:
t2['body'] = t2['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t2.head()

label                       body
0      1           [taipei, taiwan]
1      1  [macao, taiwan, shanghai]
2      0           [japan, sapporo]
3      0   [sapporo, osaka, taiwan]
4      0  [taiwan, taiwan, sapporo]

In [81]:
t3['body'] = t3['body'].apply(lambda x: [stemmer.stem(y) for y in x])
t3.head()

label                        body
0      1  [send, us, your, password]
1      0    [send, us, your, review]
2      0    [review, your, password]
3      1                [review, us]
4      1      [send, your, password]

In [82]:
t1['body'] = t1['body'].apply(lambda x: ' '.join(x))
t1.head()

label                              body
0      1                chines beij chines
1      1            chines chines shanghai
2      1                      chines macao
3      0                tokyo japan chines
4      1  chines chines chines tokyo japan

In [83]:
t2['body'] = t2['body'].apply(lambda x: ' '.join(x))
t2.head()

label                   body
0      1          taipei taiwan
1      1  macao taiwan shanghai
2      0          japan sapporo
3      0   sapporo osaka taiwan
4      0  taiwan taiwan sapporo

In [84]:
t3['body'] = t3['body'].apply(lambda x: ' '.join(x))
t3

label                   body
0      1  send us your password
1      0    send us your review
2      0   review your password
3      1              review us
4      1     send your password
5      1   send us your account
6      0          review us now

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
counts_vect = CountVectorizer()#(token_pattern = r"(?u)\b\w+\b")
counts13_1 = counts_vect.fit_transform(t1['body'])
print counts13_1


  (0, 0)	1
  (0, 1)	2
  (1, 4)	1
  (1, 1)	2
  (2, 3)	1
  (2, 1)	1
  (3, 2)	1
  (3, 5)	1
  (3, 1)	1
  (4, 2)	1
  (4, 5)	1
  (4, 1)	3


In [86]:
counts13_10 = counts_vect.fit_transform(t2['body'])
print counts13_10

  (0, 6)	1
  (0, 5)	1
  (1, 4)	1
  (1, 1)	1
  (1, 6)	1
  (2, 3)	1
  (2, 0)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (4, 3)	1
  (4, 6)	2


In [87]:
countsIAML = counts_vect.fit_transform(t3['body'])
print countsIAML

  (0, 2)	1
  (0, 6)	1
  (0, 5)	1
  (0, 4)	1
  (1, 3)	1
  (1, 6)	1
  (1, 5)	1
  (1, 4)	1
  (2, 3)	1
  (2, 2)	1
  (2, 6)	1
  (3, 3)	1
  (3, 5)	1
  (4, 2)	1
  (4, 6)	1
  (4, 4)	1
  (5, 0)	1
  (5, 6)	1
  (5, 5)	1
  (5, 4)	1
  (6, 1)	1
  (6, 3)	1
  (6, 5)	1


# Splitting the data

In [88]:
from sklearn.model_selection import train_test_split
x_train13_1, x_test13_1, y_train13_1, y_test13_1 = train_test_split(counts13_1, t1['label'], test_size=0.2, shuffle=False)
x_train13_10, x_test13_10, y_train13_10, y_test13_10 = train_test_split(counts13_10, t2['label'], test_size=0.2, shuffle=False)
x_trainIAML, x_testIAML, y_trainIAML, y_testIAML = train_test_split(countsIAML, t3['label'], test_size=1, shuffle=False)

# Training the models

In [89]:
model13_1 = BernoulliNB().fit(x_train13_1, y_train13_1)
model13_10 = BernoulliNB().fit(x_train13_10, y_train13_10)
modelIAML = BernoulliNB().fit(x_trainIAML, y_trainIAML)

# Testing the models

In [98]:
predicted13_1 = model13_1.predict(x_test13_1)
predicted13_10 = model13_10.predict(x_test13_10)
predictedIAML = modelIAML.predict(x_testIAML)

print("Table 13.1 (1 in China, 0 not in China)")
print(predicted13_1)
print("Table 13.10 (1 in China, 0 not in China)")
print(predicted13_10)
print("Table IAML (0 ham - 1 spam)")
print(predictedIAML)

Table 13.1 (1 in China, 0 not in China)
[0]
Table 13.10 (1 in China, 0 not in China)
[0]
Table IAML (0 ham - 1 spam)
[0]


# Multinomial-Bernoulli comparison

The results for both methods are shown in the next table.

Table 13.1 (1 in China, 0 not in China)

Table 13.10 (1 in China, 0 not in China)

Table IAML (0 ham - 1 spam)



|             | Multinomial classification | Bernoulli Classification |
|:-----------:|:-------------------------:|:-----------------------:|
|  Table 13.1 |              1            |             0           |
| Table 13.10 |              0            |             0           |
|  Table IAML |              0            |             0           |




The only difference between the tow models in the datasets used is in the classification for table 13.1, where Bernoulli method is classifying it as 0 (not in China), which is wrong, this is more likely happening because Bernoulli may classify to a wrong class for a single term occurrence, in this case for the terms "Japan" and "Tokyo".